[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Cache optimization
[[build.caching]]
  path = "node_modules/.cache"
  max_size = "100mb"

[[build.caching]]
  path = ".next/cache"
  max_size = "50mb"

# Explicitly exclude large caches
[build.caching.exclude]
  - "node_modules/**/*"
  - "*.log"
  - ".git/**/*"
